### ISSUE TITLE
Array to string conversion in widget.php line 1886

### ISSUE THREAD

**Issue by lmartins** [wpsmith/genesis-sandbox-featured-content-widget#41]
This seems to be causing two problems:

1. White screen error when enabling the plugin in a multisite network site
2. Notice while editing the widget as shown here:
https://www.dropbox.com/s/o8edttvtu5qvngb/Screenshot%202014-09-23%2009.32.38.png?dl=0

Thanks.

**Comment by wpsmith** [comment]
Fixed in 1.2.0.
