### ISSUE TITLE
Change default post-info and post-meta shortcodes

### ISSUE THREAD

**Issue by cre8tivediva** [wpsmith/genesis-sandbox-featured-content-widget#46]
I'm not quite sure if I should be posting this here or if I should post it on the plugin support page on Wordpress.org. Please let me know for future reference.

I am wanting to share the plugin with a theme I am considering, however it would require them to make the same edits to these areas over and over. Is there a way to reset the default settings i.e., change these - [post_date] By [post_author_posts_link] [post_comments] - so that when they drag them over - whether it's 1, 5, 8 - they show the new settings I have added in there.

I use Genesis Simple Edits to modify the output on each post and it works great, but I cannot figure out how to do it with the widget.

I love all the features inside this plugin.

Again, if I posted this in the wrong place, please let me know. Thank you.

**Comment by wpsmith** [comment]
What theme is it? If you can modify the functions.php file within the theme, then you can filter `gsfc_defaults` to make whatever settings you would like.
