### ISSUE TITLE
<article> hook

### ISSUE THREAD

**Issue by simbasounds** [wpsmith/genesis-sandbox-featured-content-widget#49]
I'm using this technique to create justified blocks: http://www.barrelny.com/blog/text-align-justify-and-rwd/

In order to apply it to the plugin's output I need to insert a space after </article>, but I don't think there's a hook for that.

**Comment by wpsmith** [comment]
No, that's not needed. You can hook into the `post_class` filter and use the `$gs_counter` to determine which number you are on and add your own class for breakage. So assuming you want to break on the 4th one, it would be something like this:
````
add_filter( 'post_class', 'prefix_post_class' );
function prefix_post_class( $classes ) {
    global $gs_counter;
    $classes[] = ( $gs_counter + 1 ) % 4 ? 'break';
    return $classes;
}
````
