### ISSUE TITLE
Typo for one-sixth columns

### ISSUE THREAD

**Issue by sarahfogle** [wpsmith/genesis-sandbox-featured-content-widget#50]
When using the One Sixth option, there appears to be a typo in the assigned class (".one-sixith"):
![image](https://cloud.githubusercontent.com/assets/7316590/5589741/423c2ef6-90f4-11e4-9637-b0ced895805e.png)

It is also making each post ".first", which is rendering all posts as the first post in the column, so all of the posts stack instead of line up side by side.

There is only one file I can see that has the "sixith" typo, genesis-featured-content-widget/widget.php, but correcting it does not seem to resolve the problem.

**Comment by electricbrick** [comment]
Also an issue for me.

**Comment by wpsmith** [comment]
Fixed. 1.2
