### ISSUE TITLE
Filter or Hook for excerpt_more

### ISSUE THREAD

**Issue by nikcree** [wpsmith/genesis-sandbox-featured-content-widget#51]
Is there a filter or hook for the excerpt_more and the_content_more_link. I would like to add a div around the more link to provide more control for styling as a button.

(PS I posted this also at https://wordpress.org/support/topic/filter-or-hook-for-excerpt-read-more?replies=1 before realising that you support the plugin here) - Thanks Again

**Comment by wpsmith** [comment]
excerpt_more filters excerpt_more. So if you would like to filter it, then you can, just hook in after the widget at priority 11+.
`add_filter( 'excerpt_more', 'prefix_excerpt_more', 11 );`

For get_the_content_more_link, use the Genesis `get_the_content_more_link` filter likewise.
`add_filter( 'get_the_content_more_link', 'prefix_get_the_content_more_link', 11 );`

Please let me know if this works for you. As it stands at the moment, I do not believe this to be an issue.
