### ISSUE TITLE
Post Info + Featured Image Before Title ordering

### ISSUE THREAD

**Issue by electricbrick** [wpsmith/genesis-sandbox-featured-content-widget#52]
When you set post info and a posts featured images to render 'Before Title', post info actually shows before the featured image, which I doubt mostly anyone would want. I've tried to dig through the plugin source to figure out how to force the load order within that hook to no avail. A means of prioritizing one over the other via the widget is desirable, but at a minimum I'd love to get a snippet for filtering the load order to throw into my functions file.

![screen shot 2015-01-27 at 12 26 49 pm](https://cloud.githubusercontent.com/assets/2481417/5923219/d0754f46-a61f-11e4-82fb-5b5ff11ad49d.png)

**Comment by wpsmith** [comment]
Thanks. I submitted a commit. Would you mind testing?
